/**
 * Ledger symbols and quote symbols must be identical. Keeping this catalogue
 * in one place prevents a transaction logged as BTC from being valued using a
 * different market instrument. `CRYPTO:<CoinGecko id>` is provider-neutral at
 * the UI level while still resolving unambiguously to its market-data asset.
 */
export const CRYPTO_ASSETS = [
  { symbol: "CRYPTO:bitcoin", ticker: "BTC", name: "Bitcoin" },
  { symbol: "CRYPTO:ethereum", ticker: "ETH", name: "Ethereum" },
  { symbol: "CRYPTO:tether", ticker: "USDT", name: "Tether" },
  { symbol: "CRYPTO:binancecoin", ticker: "BNB", name: "BNB" },
  { symbol: "CRYPTO:ripple", ticker: "XRP", name: "XRP" },
  { symbol: "CRYPTO:solana", ticker: "SOL", name: "Solana" },
  { symbol: "CRYPTO:usd-coin", ticker: "USDC", name: "USDC" },
  { symbol: "CRYPTO:tron", ticker: "TRX", name: "TRON" },
  { symbol: "CRYPTO:dogecoin", ticker: "DOGE", name: "Dogecoin" },
  { symbol: "CRYPTO:cardano", ticker: "ADA", name: "Cardano" },
  { symbol: "CRYPTO:hyperliquid", ticker: "HYPE", name: "Hyperliquid" },
  { symbol: "CRYPTO:avalanche-2", ticker: "AVAX", name: "Avalanche" },
  { symbol: "CRYPTO:sui", ticker: "SUI", name: "Sui" },
  { symbol: "CRYPTO:chainlink", ticker: "LINK", name: "Chainlink" },
  { symbol: "CRYPTO:stellar", ticker: "XLM", name: "Stellar" },
  { symbol: "CRYPTO:toncoin", ticker: "TON", name: "Toncoin" },
  { symbol: "CRYPTO:shiba-inu", ticker: "SHIB", name: "Shiba Inu" },
  { symbol: "CRYPTO:hedera-hashgraph", ticker: "HBAR", name: "Hedera" },
  { symbol: "CRYPTO:bitcoin-cash", ticker: "BCH", name: "Bitcoin Cash" },
  { symbol: "CRYPTO:polkadot", ticker: "DOT", name: "Polkadot" },
  { symbol: "CRYPTO:litecoin", ticker: "LTC", name: "Litecoin" },
  { symbol: "CRYPTO:uniswap", ticker: "UNI", name: "Uniswap" },
  { symbol: "CRYPTO:near", ticker: "NEAR", name: "NEAR Protocol" },
  { symbol: "CRYPTO:dai", ticker: "DAI", name: "Dai" },
  { symbol: "CRYPTO:internet-computer", ticker: "ICP", name: "Internet Computer" },
  { symbol: "CRYPTO:aptos", ticker: "APT", name: "Aptos" },
  { symbol: "CRYPTO:monero", ticker: "XMR", name: "Monero" },
  { symbol: "CRYPTO:cosmos", ticker: "ATOM", name: "Cosmos" },
  { symbol: "CRYPTO:ethereum-classic", ticker: "ETC", name: "Ethereum Classic" },
  { symbol: "CRYPTO:filecoin", ticker: "FIL", name: "Filecoin" },
  { symbol: "CRYPTO:arbitrum", ticker: "ARB", name: "Arbitrum" },
  { symbol: "CRYPTO:optimism", ticker: "OP", name: "Optimism" },
  { symbol: "CRYPTO:aave", ticker: "AAVE", name: "Aave" },
  { symbol: "CRYPTO:render-token", ticker: "RENDER", name: "Render" },
  { symbol: "CRYPTO:injective-protocol", ticker: "INJ", name: "Injective" },
  { symbol: "CRYPTO:algorand", ticker: "ALGO", name: "Algorand" },
  { symbol: "CRYPTO:vechain", ticker: "VET", name: "VeChain" },
  { symbol: "CRYPTO:the-graph", ticker: "GRT", name: "The Graph" },
  { symbol: "CRYPTO:maker", ticker: "MKR", name: "Maker" },
  { symbol: "CRYPTO:the-sandbox", ticker: "SAND", name: "The Sandbox" },
  { symbol: "CRYPTO:figure-heloc", ticker: "FIGR_HELOC", name: "Figure Heloc" },
  { symbol: "CRYPTO:zcash", ticker: "ZEC", name: "Zcash" },
  { symbol: "CRYPTO:rain", ticker: "RAIN", name: "Rain" },
  { symbol: "CRYPTO:usds", ticker: "USDS", name: "USDS" },
  { symbol: "CRYPTO:whitebit", ticker: "WBT", name: "WhiteBIT Coin" },
  { symbol: "CRYPTO:leo-token", ticker: "LEO", name: "LEO Token" },
  { symbol: "CRYPTO:ethena-usde", ticker: "USDE", name: "Ethena USDe" },
  { symbol: "CRYPTO:usd1-wlfi", ticker: "USD1", name: "USD1" },
  { symbol: "CRYPTO:canton-network", ticker: "CC", name: "Canton" },
  { symbol: "CRYPTO:the-open-network", ticker: "GRAM", name: "Gram (prev. Toncoin)" },
  { symbol: "CRYPTO:global-dollar", ticker: "USDG", name: "Global Dollar" },
  { symbol: "CRYPTO:crypto-com-chain", ticker: "CRO", name: "Cronos" },
  { symbol: "CRYPTO:paypal-usd", ticker: "PYUSD", name: "PayPal USD" },
  { symbol: "CRYPTO:blackrock-usd-institutional-digital-liquidity-fund", ticker: "BUIDL", name: "BlackRock USD Institutional Digital Liquidity Fund" },
  { symbol: "CRYPTO:tether-gold", ticker: "XAUT", name: "Tether Gold" },
  { symbol: "CRYPTO:bittensor", ticker: "TAO", name: "Bittensor" },
  { symbol: "CRYPTO:hashnote-usyc", ticker: "USYC", name: "Circle USYC" },
  { symbol: "CRYPTO:memecore", ticker: "M", name: "MemeCore" },
  { symbol: "CRYPTO:okb", ticker: "OKB", name: "OKB" },
  { symbol: "CRYPTO:ondo-finance", ticker: "ONDO", name: "Ondo" },
  { symbol: "CRYPTO:official-trump", ticker: "TRUMP", name: "Official Trump" },
  { symbol: "CRYPTO:kaspa", ticker: "KAS", name: "Kaspa" },
  { symbol: "CRYPTO:bitget-token", ticker: "BGB", name: "Bitget Token" },
  { symbol: "CRYPTO:immutable-x", ticker: "IMX", name: "Immutable" },
  { symbol: "CRYPTO:thorchain", ticker: "RUNE", name: "THORChain" },
  { symbol: "CRYPTO:lido-dao", ticker: "LDO", name: "Lido DAO" },
  { symbol: "CRYPTO:rocket-pool", ticker: "RPL", name: "Rocket Pool" },
  { symbol: "CRYPTO:gala", ticker: "GALA", name: "Gala" },
  { symbol: "CRYPTO:decentraland", ticker: "MANA", name: "Decentraland" },
  { symbol: "CRYPTO:axie-infinity", ticker: "AXS", name: "Axie Infinity" },
  { symbol: "CRYPTO:curve-dao-token", ticker: "CRV", name: "Curve DAO Token" },
  { symbol: "CRYPTO:convex-finance", ticker: "CVX", name: "Convex Finance" },
  { symbol: "CRYPTO:fantom", ticker: "FTM", name: "Fantom" },
  { symbol: "CRYPTO:flow", ticker: "FLOW", name: "Flow" },
  { symbol: "CRYPTO:mina-protocol", ticker: "MINA", name: "Mina Protocol" },
  { symbol: "CRYPTO:dydx", ticker: "DYDX", name: "dYdX" },
    // Additional assets
  { symbol: "CRYPTO:pepe", ticker: "PEPE", name: "Pepe" },
  { symbol: "CRYPTO:bonk", ticker: "BONK", name: "Bonk" },
  { symbol: "CRYPTO:dogwifcoin", ticker: "WIF", name: "dogwifhat" },
  { symbol: "CRYPTO:floki", ticker: "FLOKI", name: "FLOKI" },
  { symbol: "CRYPTO:jupiter-exchange-solana", ticker: "JUP", name: "Jupiter" },
  { symbol: "CRYPTO:pyth-network", ticker: "PYTH", name: "Pyth Network" },
  { symbol: "CRYPTO:celestia", ticker: "TIA", name: "Celestia" },
  { symbol: "CRYPTO:sei-network", ticker: "SEI", name: "Sei" },
  { symbol: "CRYPTO:blockstack", ticker: "STX", name: "Stacks" },
  { symbol: "CRYPTO:ordinals", ticker: "ORDI", name: "ORDI" },
  { symbol: "CRYPTO:worldcoin-wld", ticker: "WLD", name: "Worldcoin" },
  { symbol: "CRYPTO:ethereum-name-service", ticker: "ENS", name: "Ethereum Name Service" },
  { symbol: "CRYPTO:1inch", ticker: "1INCH", name: "1inch" },
  { symbol: "CRYPTO:compound-governance-token", ticker: "COMP", name: "Compound" },
  { symbol: "CRYPTO:havven", ticker: "SNX", name: "Synthetix" },
  { symbol: "CRYPTO:yearn-finance", ticker: "YFI", name: "yearn.finance" },
  { symbol: "CRYPTO:loopring", ticker: "LRC", name: "Loopring" },
  { symbol: "CRYPTO:enjincoin", ticker: "ENJ", name: "Enjin Coin" },
  { symbol: "CRYPTO:chiliz", ticker: "CHZ", name: "Chiliz" },
  { symbol: "CRYPTO:basic-attention-token", ticker: "BAT", name: "Basic Attention Token" },
  { symbol: "CRYPTO:kusama", ticker: "KSM", name: "Kusama" },
  { symbol: "CRYPTO:neo", ticker: "NEO", name: "NEO" },
  { symbol: "CRYPTO:iota", ticker: "IOTA", name: "IOTA" },
  { symbol: "CRYPTO:qtum", ticker: "QTUM", name: "Qtum" },
  { symbol: "CRYPTO:ontology", ticker: "ONT", name: "Ontology" },
  { symbol: "CRYPTO:omisego", ticker: "OMG", name: "OMG Network" },
  { symbol: "CRYPTO:digibyte", ticker: "DGB", name: "DigiByte" },
  { symbol: "CRYPTO:ravencoin", ticker: "RVN", name: "Ravencoin" },
  { symbol: "CRYPTO:siacoin", ticker: "SC", name: "Siacoin" },
  { symbol: "CRYPTO:decred", ticker: "DCR", name: "Decred" },
  { symbol: "CRYPTO:dash", ticker: "DASH", name: "Dash" },
  { symbol: "CRYPTO:horizen", ticker: "ZEN", name: "Horizen" },
  { symbol: "CRYPTO:komodo", ticker: "KMD", name: "Komodo" },
  { symbol: "CRYPTO:arweave", ticker: "AR", name: "Arweave" },
  { symbol: "CRYPTO:helium", ticker: "HNT", name: "Helium" },
  { symbol: "CRYPTO:akash-network", ticker: "AKT", name: "Akash Network" },
  { symbol: "CRYPTO:fetch-ai", ticker: "FET", name: "Fetch.ai" },
  { symbol: "CRYPTO:ocean-protocol", ticker: "OCEAN", name: "Ocean Protocol" },
  { symbol: "CRYPTO:singularitynet", ticker: "AGIX", name: "SingularityNET" },
  { symbol: "CRYPTO:numeraire", ticker: "NMR", name: "Numeraire" },
  { symbol: "CRYPTO:band-protocol", ticker: "BAND", name: "Band Protocol" },
  { symbol: "CRYPTO:api3", ticker: "API3", name: "API3" },
  { symbol: "CRYPTO:uma", ticker: "UMA", name: "UMA" },
  { symbol: "CRYPTO:balancer", ticker: "BAL", name: "Balancer" },
  { symbol: "CRYPTO:sushi", ticker: "SUSHI", name: "SushiSwap" },
  { symbol: "CRYPTO:0x", ticker: "ZRX", name: "0x" },
  { symbol: "CRYPTO:ankr", ticker: "ANKR", name: "Ankr" },
  { symbol: "CRYPTO:celo", ticker: "CELO", name: "Celo" },
  { symbol: "CRYPTO:harmony", ticker: "ONE", name: "Harmony" },
  { symbol: "CRYPTO:zilliqa", ticker: "ZIL", name: "Zilliqa" },
  { symbol: "CRYPTO:icon", ticker: "ICX", name: "ICON" },
  { symbol: "CRYPTO:theta-token", ticker: "THETA", name: "Theta Network" },
  { symbol: "CRYPTO:theta-fuel", ticker: "TFUEL", name: "Theta Fuel" },
  { symbol: "CRYPTO:holotoken", ticker: "HOT", name: "Holo" },
  { symbol: "CRYPTO:golem", ticker: "GLM", name: "Golem" },
  { symbol: "CRYPTO:status", ticker: "SNT", name: "Status" },
  { symbol: "CRYPTO:storj", ticker: "STORJ", name: "Storj" },
  { symbol: "CRYPTO:verge", ticker: "XVG", name: "Verge" },
  { symbol: "CRYPTO:grin", ticker: "GRIN", name: "Grin" },
  { symbol: "CRYPTO:ergo", ticker: "ERG", name: "Ergo" },
  { symbol: "CRYPTO:conflux-token", ticker: "CFX", name: "Conflux" },
  { symbol: "CRYPTO:klay-token", ticker: "KLAY", name: "Klaytn" },
  { symbol: "CRYPTO:ronin", ticker: "RON", name: "Ronin" },
  { symbol: "CRYPTO:gmx", ticker: "GMX", name: "GMX" },
  { symbol: "CRYPTO:pendle", ticker: "PENDLE", name: "Pendle" },
  { symbol: "CRYPTO:ethena", ticker: "ENA", name: "Ethena" },
  { symbol: "CRYPTO:jito-governance-token", ticker: "JTO", name: "Jito" },
  { symbol: "CRYPTO:wormhole", ticker: "W", name: "Wormhole" },
  { symbol: "CRYPTO:blur", ticker: "BLUR", name: "Blur" },
  { symbol: "CRYPTO:apecoin", ticker: "APE", name: "ApeCoin" },
  { symbol: "CRYPTO:illuvium", ticker: "ILV", name: "Illuvium" },
  { symbol: "CRYPTO:gods-unchained", ticker: "GODS", name: "Gods Unchained" },
  { symbol: "CRYPTO:wax", ticker: "WAXP", name: "WAX" },
  { symbol: "CRYPTO:gas", ticker: "GAS", name: "Gas" },
  { symbol: "CRYPTO:aleph-zero", ticker: "AZERO", name: "Aleph Zero" },
  { symbol: "CRYPTO:astar", ticker: "ASTR", name: "Astar" },
  { symbol: "CRYPTO:moonbeam", ticker: "GLMR", name: "Moonbeam" },
  { symbol: "CRYPTO:moonriver", ticker: "MOVR", name: "Moonriver" },
  { symbol: "CRYPTO:centrifuge", ticker: "CFG", name: "Centrifuge" },
  { symbol: "CRYPTO:phala", ticker: "PHA", name: "Phala Network" },
  { symbol: "CRYPTO:litentry", ticker: "LIT", name: "Litentry" },
  { symbol: "CRYPTO:kilt-protocol", ticker: "KILT", name: "KILT Protocol" },
  { symbol: "CRYPTO:acala", ticker: "ACA", name: "Acala" },
  { symbol: "CRYPTO:parallel-finance", ticker: "PARA", name: "Parallel Finance" },
  { symbol: "CRYPTO:interlay", ticker: "INTR", name: "Interlay" },
  { symbol: "CRYPTO:clover-finance", ticker: "CLV", name: "Clover Finance" },
  { symbol: "CRYPTO:efinity", ticker: "EFI", name: "Efinity" },
  { symbol: "CRYPTO:unique-network", ticker: "UNQ", name: "Unique Network" },
  { symbol: "CRYPTO:xdce-crowd-sale", ticker: "XDC", name: "XDC Network" },
  { symbol: "CRYPTO:ecash", ticker: "XEC", name: "eCash" },
  { symbol: "CRYPTO:kava", ticker: "KAVA", name: "Kava" },
  { symbol: "CRYPTO:oasis-network", ticker: "ROSE", name: "Oasis Network" },
  { symbol: "CRYPTO:nervos-network", ticker: "CKB", name: "Nervos Network" },
  { symbol: "CRYPTO:osmosis", ticker: "OSMO", name: "Osmosis" },
  { symbol: "CRYPTO:secret", ticker: "SCRT", name: "Secret" },
  { symbol: "CRYPTO:zelcash", ticker: "FLUX", name: "Flux" },
  { symbol: "CRYPTO:deso", ticker: "DESO", name: "Decentralized Social" },
  { symbol: "CRYPTO:kadena", ticker: "KDA", name: "Kadena" },
  { symbol: "CRYPTO:elrond-erd-2", ticker: "EGLD", name: "MultiversX" },
  { symbol: "CRYPTO:core", ticker: "CORE", name: "Core" },
  { symbol: "CRYPTO:bitcoin-cash-sv", ticker: "BSV", name: "Bitcoin SV" },
  { symbol: "CRYPTO:bitcoin-gold", ticker: "BTG", name: "Bitcoin Gold" },
  { symbol: "CRYPTO:bitcoin-diamond", ticker: "BCD", name: "Bitcoin Diamond" },
  { symbol: "CRYPTO:tezos", ticker: "XTZ", name: "Tezos" },
] as const;

export type CryptoAssetDefinition = (typeof CRYPTO_ASSETS)[number];

export const isCryptoSymbol = (symbol: string) => symbol.startsWith("CRYPTO:");
